name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the files
      uses: actions/checkout@v4

    - name: Update permissions on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SERVIDORA1 }}
        script: |
          cd /var/www
          sudo chown -R $USER:www-data html
          cd /var/www/html/DWS2/CursoLaravel
          sudo chown -R $USER:www-data storage
          sudo chown -R $USER:www-data bootstrap/cache
          sudo chmod -R 775 storage
          sudo chmod -R 775 bootstrap/cache

    - name: Copy files with SSH
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVIDORA1 }} 
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "./"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: "/var/www/html/DWS2"
        EXCLUDE: "/dist/, /CursoLaravel/node_modules/, /CursoLaravel/vendor, /CursoLaravel/public/img/events, **.env"

    - name: Execute deploy script on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SERVIDORA1 }}
        script: |
          cd /var/www/html/DWS2/CursoLaravel
          composer install --no-dev --optimize-autoloader
          npm install
          npm run build
          php artisan migrate --force
          php artisan optimize:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          cd /var/www
          sudo chown -R $USER:www-data html
          cd /var/www/html/CursoLaravel
          sudo chown -R $USER:www-data storage
          sudo chown -R $USER:www-data bootstrap/cache
          sudo chmod -R 775 storage
          sudo chmod -R 775 bootstrap/cache
          sudo service apache2 restart